### ISSUE TITLE
升级最新mac版本过后swift build 会报错

### ISSUE THREAD

**Issue by sjo146** [reers/Rhea#1]
按照package.swift里面标明的swift编译运行，会报错no type named 'BitwiseCopyable' in module 'Swift'，google了一下下，发现BitwiseCopyable是swift6.0以后的特性，然后把package.swift改为6.0编译过后，报错static property 'load' is not concurrency-safe because non-'Sendable' type 'RheaEvent' may have shared mutable state，下面是所有现场信息

`error: static property 'normal' is not concurrency-safe because non-'Sendable' type 'RheaPriority' may have shared mutable state
12 | /// This struct allows for both predefined priority levels and custom integer-based priorities.
13 | /// It conforms to ExpressibleByIntegerLiteral, allowing direct use of integer values for priorities.
14 | public struct RheaPriority: ExpressibleByIntegerLiteral, Equatable, Hashable, RawRepresentable {
   |               `- note: consider making struct 'RheaPriority' conform to the 'Sendable' protocol
15 |     public typealias IntegerLiteral = Int
16 |     public init(integerLiteral value: Int) {
   :
38 |     public static let low: RheaPriority = 3
39 |     /// Callback function receive the normal priority for execution.
40 |     public static let normal: RheaPriority = 5
   |                       |- error: static property 'normal' is not concurrency-safe because non-'Sendable' type 'RheaPriority' may have shared mutable state
   |                       |- note: annotate 'normal' with '@MainActor' if property should only be accessed from the main actor
   |                       `- note: disable concurrency-safety checks if accesses are protected by an external synchronization mechanism
41 |     /// Callback function receive high priority for execution.
42 |     public static let high: RheaPriority = 7`

是不是是因为目前库还没适配swift6导致的呢

**Comment by vnixx** [comment]
已适配 Swift 6
